apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: piomin/cloudadminserver
        imagePullPolicy: Never
        env:
            - name: TZ
              value: America/New_York
        ports:
        - containerPort: 8080
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: admin
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          enabled: true
          secrets:
            enable-api: true
          discovery:
            enabled: true
            all-namespaces: true
            service-labels:
              spring-boot: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  type: NodePort
  selector:
    app: admin
  ports:
  - port: 8088
    targetPort: 8080
  type: LoadBalancer
